### ISSUE TITLE
Unresolved import `syn::export`

### ISSUE THREAD

**Issue by charles-r-earp** [NyxCode/proxy-enum#3]
It looks like the latest version of syn has removed the export module (it's now private).
  
    error[E0432]: unresolved import `syn::export`
       --> src/lib.rs:138:10
        |
    138 | use syn::export::TokenStream2;
        |          ^^^^^^ could not find `export` in `syn`

**Comment by NyxCode** [comment]
Oh, thanks for raising the issue. It's fixed in 0.3.1.
